#!/bin/bash

set -e

runTests() {
  TEST_DATABASE_URL=$1 go test
  pushd migrate
  TEST_DATABASE_URL=$1 go test
  popd
}

if [ -z ${TEST_MYSQL_DATABASE_URL+x} ]; then 
	echo "TEST_MYSQL_DATABASE_URL not set, only testing sqlite3"
else 
	runTests $TEST_MYSQL_DATABASE_URL
fi

# blank host + path keeps sqlite3 in memory
runTests sqlite3://

